package com.example.booksstore.Presenter;

import android.content.Context;
import android.util.Log;

import com.example.booksstore.Books.Books;
import com.example.booksstore.Database.BooksDatabase;
import com.example.booksstore.R;

import java.util.ArrayList;

import static android.content.ContentValues.TAG;

public class BooksPresenter {
    private Context context;
    private  BooksDatabase booksDatabase;

    public BooksPresenter(Context context) {
        this.context = context;
        booksDatabase = new BooksDatabase(context);
    }

    public ArrayList<Books> getBooksFromDatabase(){
        return booksDatabase.getAllBooks();
    }
    public ArrayList<Books> getFavouriteBooksFromDatabase(int isfav){
        return booksDatabase.getFavouriteBooks(isfav);
    }
    public ArrayList<Books> getBooksType(String type){
        return booksDatabase.getBooksType(type);
    }
    public ArrayList<Books> getPopularBooks(){
        return booksDatabase.getPopularBooks();
    }
    public void updateBooks(Books books){
        booksDatabase.update(books);
    }
    public   void  addBooks(){
        String historyType="History";
        String programingType ="Programing";
        String kidsType="Kids";
        booksDatabase.insert(new Books(R.drawable.acient_world,"Acient World","Arnold Costa",4,0,historyType,"Ancient history as a term refers to the aggregate of past events[1] from the beginning of writing and recorded human history and extending as far as post-classical history. The phrase may be used either to refer to the period of time or the academic discipline.\n" +
                "\n" +
                "The span of recorded history is roughly 5,000 years, beginning with the Sumerian cuneiform script, with the oldest coherent texts from about 2600 BC.[2] Ancient history covers all continents inhabited by humans in the period 3000 BC – AD 500.\n" +
                "\n" +
                "The broad term \"ancient history\" is not to be confused with \"classical antiquity\". The term classical antiquity is often used to refer to Western history in the Ancient Mediterranean from the beginning of recorded Greek history in 776 BC (first Olympiad). This roughly coincides with the traditional date of the founding of Rome in 753 BC, the beginning of the history of ancient Rome, and the beginning of the Archaic period in Ancient Greece.\n" +
                "\n" +
                "The academic term \"history\" is not to be confused with colloquial references to times past. History is fundamentally the study of the past, and can be either scientific (archaeology) or humanistic (history through language).\n" +
                "\n" +
                "Although the ending date of ancient history is disputed, some Western scholars use the fall of the Western Roman Empire in 476 AD (the most used),[3][4] the closure of the Platonic Academy in 529 AD,[5] the death of the emperor Justinian I in 565 AD,[6] the coming of Islam,[7] or the rise of Charlemagne[8] as the end of ancient and Classical European history. Outside of Europe the 450–500 time frame for the end of ancient times has had difficulty as a transition date from ancient to post-classical times.\n" +
                "\n" +
                "During the time period of ancient history (starting roughly from 3000 BC), the world population was already exponentially increasing due to the Neolithic Revolution, which was in full progress. According to HYDE estimates from the Netherlands, world population increased exponentially in this period. In 10,000 BC in prehistory, the world population had stood at 2 million, rising to 45 million by 3,000 BC. By the rise of the Iron Age in 1,000 BC, the population had risen to 72 million. By the end of the period in 500 AD, the world population is thought to have stood at 209 million. In 3,500 years, the world population increased by 100 times."));
        booksDatabase.insert(new Books(R.drawable.american_president,"American Presidant","Mahmoud Mostafa",2,0,historyType,"Ancient history as a term refers to the aggregate of past events[1] from the beginning of writing and recorded human history and extending as far as post-classical history. The phrase may be used either to refer to the period of time or the academic discipline.\n" +
                "\n" +
                "The span of recorded history is roughly 5,000 years, beginning with the Sumerian cuneiform script, with the oldest coherent texts from about 2600 BC.[2] Ancient history covers all continents inhabited by humans in the period 3000 BC – AD 500.\n" +
                "\n" +
                "The broad term \"ancient history\" is not to be confused with \"classical antiquity\". The term classical antiquity is often used to refer to Western history in the Ancient Mediterranean from the beginning of recorded Greek history in 776 BC (first Olympiad). This roughly coincides with the traditional date of the founding of Rome in 753 BC, the beginning of the history of ancient Rome, and the beginning of the Archaic period in Ancient Greece.\n" +
                "\n" +
                "The academic term \"history\" is not to be confused with colloquial references to times past. History is fundamentally the study of the past, and can be either scientific (archaeology) or humanistic (history through language).\n" +
                "\n" +
                "Although the ending date of ancient history is disputed, some Western scholars use the fall of the Western Roman Empire in 476 AD (the most used),[3][4] the closure of the Platonic Academy in 529 AD,[5] the death of the emperor Justinian I in 565 AD,[6] the coming of Islam,[7] or the rise of Charlemagne[8] as the end of ancient and Classical European history. Outside of Europe the 450–500 time frame for the end of ancient times has had difficulty as a transition date from ancient to post-classical times.\n" +
                "\n" +
                "During the time period of ancient history (starting roughly from 3000 BC), the world population was already exponentially increasing due to the Neolithic Revolution, which was in full progress. According to HYDE estimates from the Netherlands, world population increased exponentially in this period. In 10,000 BC in prehistory, the world population had stood at 2 million, rising to 45 million by 3,000 BC. By the rise of the Iron Age in 1,000 BC, the population had risen to 72 million. By the end of the period in 500 AD, the world population is thought to have stood at 209 million. In 3,500 years, the world population increased by 100 times."));
        booksDatabase.insert(new Books(R.drawable.chronocles_old_west,"Chronicles Old West","Arnold Costa",4,0,historyType,"The last events in Chronicles take place in the reign of Cyrus the Great, the Persian king who conquered Babylon in 539 BC; this sets the earliest possible date for the book.\n" +
                "\n" +
                "Chronicles appears to be largely the work of a single individual. The writer was probably male, probably a Levite (temple priest), and probably from Jerusalem. He was well-read, a skilled editor, and a sophisticated theologian. His intention was to use Israel's past to convey religious messages to his peers, the literary and political elite of Jerusalem in the time of the Achaemenid Empire.[7]\n" +
                "\n" +
                "Jewish and Christian tradition identified this author as the 5th century BC figure Ezra, who gives his name to the Book of Ezra; Ezra is also believed to be the author of both Chronicles and Ezra–Nehemiah. Later critics, skeptical of the long-maintained tradition, preferred to call the author \"the Chronicler\". However, many scholars maintain support for Ezra's authorship, not only based on centuries of work by Jewish historians, but also due to the consistency of language and speech patterns between Chronicles and Ezra-Nehemiah. Professor Emeritus Menahem Haran of the Hebrew University of Jerusalem explains, \"the overall unity of the Chronistic Work is … demonstrated by a common ideology, the uniformity of legal, cultic and historical conceptions and specific style, all of which reflect one opus.\"[9]\n" +
                "\n" +
                "One of the most striking, although inconclusive, features of Chronicles is that its closing sentence is repeated as the opening of Ezra–Nehemiah.[7] These repeated verses are called “catch-lines.” In antiquity, catch-lines were often placed at the end of a scroll to facilitate the reader’s passing on to the correct second book-scroll after completing the first. This scribal device was employed in works that exceeded the scope of a single scroll and had to be continued on another scroll.[10]\n" +
                "\n" +
                "The latter half of the 20th century, amid growing skepticism in academia regarding history in Biblical tradition, saw a reappraisal of the authorship question. Though there is a general lack of corroborating evidence, many now regard it as improbable that the author of Chronicles was also the author of the narrative portions of Ezra–Nehemiah.[11] These critics suggest it was probably composed between 400–250 BC, with the period 350–300 BC the most likely.[7] This timeframe is achieved by estimates made based on genealogies appearing in the Greek Septuagint. This theory bases its premise on latest person mentioned in Chronicles, Anani. Anani is an eighth-generation descendant of King Jehoiachin according to the Masoretic Text. They roughly estimate Anani's birth to have been sometime between 425 and 400 BC[citation needed] using an additional five generations in the genealogy of Anani appearing in the Septuagint. Based on this, the theory has persuaded many supporters of the Septuagint's reading to place Anani's likely date of birth a century later than what has been largely accepted for two millennia.[12] "));
        booksDatabase.insert(new Books(R.drawable.computer_programing,"Computer Programing","Oliver Sam",2,0,programingType,"Computer programming (often shortened to programming) is a process that leads from an original formulation of a computing problem to executable computer programs. Programming involves activities such as analysis, developing understanding, generating algorithms, verification of requirements of algorithms including their correctness and resources consumption, and implementation (commonly referred to as coding) of algorithms in a target programming language.[1]\n" +
                "\n" +
                "This course comprises nine lessons on the fundamentals of computer programming. Each lesson includes a combination of Wikibooks, Wikipedia, and Internet-based readings, YouTube videos, and hands-on, interactive learning activities. Examples are provided using flowcharts, pseudocode, and a wide variety of computer programming languages.\n" +
                "This entire Wikiversity course can be downloaded in book form by selecting Download Learning Guide in the sidebar. The corresponding Wikipedia reading collection can be downloaded in book form by selecting Download Reading Guide."));
        booksDatabase.insert(new Books(R.drawable.creature,"Creature Features","Lena Walker",1,0,kidsType,"Creatures 2 was widely anticipated. It is likely that around 450,000 copies of the original Creatures had been sold by the time the game was released, and a huge following had developed behind it.\n" +
                "\n" +
                "Unfortunately, the Creatures 2 launch did not go as planned. The Early Adoption Program failed to deliver on its basic promise of being \"early\", and the game had several major flaws, the most notable of which was a deficient norn genome that lead to OHSS. Cyberlife was subsequently accused of gouging customers when they released a Life Kit with an improved genome (as well as other features) but neglected to release this as a patch to the original game until several weeks had passed.\n" +
                "\n" +
                "In addition, documentation was considered scanty, especially by those who had owned Creatures - much appeared to have been reserved for the strategy guidebook, Creatures 2: Official Strategies & Secrets. This could be a result of tighter deadlines for the manual rather than than the book (considering Mindscape's requirements for translation, packaging and distribution) or publisher-related editing of the manual for simplicity. However, these reasons did not go down well with people who had just bought a $40 game only to find that the manual's instructions for getting norns to feed did not work reliably.\n" +
                "\n" +
                "Overall, Creatures 2 was probably a commercial success (despite inadequate marketing, which affected subsequent games as well) - however, it could be seen as a strategic failure, as for many it compromised the trust between the community and Cyberlife. Much had been promised, and yet many users considered the only improvement over the original to be the graphics. Third-party developers were naturally less willing to work on a game that they did not really enjoy playing, and this probably affected the supply of COBs. Things improved after the development of the Canny Norns and Nova Subterra, but some people had lost interest by then, and it is impossible to say how many people would have become part of the community but never found out about the improved genomes and so grew prematurely tired of the game. "));
        booksDatabase.insert(new Books(R.drawable.dinasours,"Dinosaurs","Selena Adams",3,0,kidsType,"Dinosaurs are a diverse group of reptiles[note 1] of the clade Dinosauria. They first appeared during the Triassic period, between 243 and 233.23 million years ago, although the exact origin and timing of the evolution of dinosaurs is the subject of active research. They became the dominant terrestrial vertebrates after the Triassic–Jurassic extinction event 201.3 million years ago; their dominance continued throughout the Jurassic and Cretaceous periods. The fossil record shows that birds are modern feathered dinosaurs, having evolved from earlier theropods during the Late Jurassic epoch, and are the only dinosaur lineage to survive the Cretaceous–Paleogene extinction event approximately 66 million years ago. Dinosaurs can therefore be divided into avian dinosaurs, or birds; and non-avian dinosaurs, which are all dinosaurs other than birds.\n" +
                "\n" +
                "Dinosaurs are a varied group of animals from taxonomic, morphological and ecological standpoints. Using fossil evidence, paleontologists have identified over 900 distinct genera and more than 1,000 different species of non-avian dinosaurs. Dinosaurs are represented on every continent by both extant species (birds) and fossil remains. Through the first half of the 20th century, before birds were recognized to be dinosaurs, most of the scientific community believed dinosaurs to have been sluggish and cold-blooded. Most research conducted since the 1970s, however, has indicated that all dinosaurs were active animals with elevated metabolisms and numerous adaptations for social interaction. Some were herbivorous, others carnivorous. Evidence suggests that all dinosaurs were egg-laying; and that nest-building was a trait shared by many dinosaurs, both avian and non-avian.\n" +
                "\n" +
                "While dinosaurs were ancestrally bipedal, many extinct groups included quadrupedal species, and some were able to shift between these stances. Elaborate display structures such as horns or crests are common to all dinosaur groups, and some extinct groups developed skeletal modifications such as bony armor and spines. While the dinosaurs' modern-day surviving avian lineage (birds) are generally small due to the constraints of flight, many prehistoric dinosaurs (non-avian and avian) were large-bodied—the largest sauropod dinosaurs are estimated to have reached lengths of 39.7 meters (130 feet) and heights of 18 m (59 ft) and were the largest land animals of all time. Still, the idea that non-avian dinosaurs were uniformly gigantic is a misconception based in part on preservation bias, as large, sturdy bones are more likely to last until they are fossilized. Many dinosaurs were quite small, some of them only measured about 50 centimeters (20 inches) long.\n" +
                "\n" +
                "The first dinosaur fossils were recognized in the early 19th century, with the name \"dinosaur\" (meaning \"terrible lizard\") having been coined by Sir Richard Owen in 1841 to refer to these \"great fossil lizards\". Since then, mounted fossil dinosaur skeletons have been major attractions at museums worldwide, and dinosaurs have become an enduring part of popular culture. The large sizes of some dinosaurs, as well as their seemingly monstrous and fantastic nature, have ensured their regular appearance in best-selling books and films, such as Jurassic Park. Persistent public enthusiasm for the animals has resulted in significant funding for dinosaur science, and new discoveries are regularly covered by the media. "));
        booksDatabase.insert(new Books(R.drawable.ds,"Data Structure","ClaraJames",2,0,programingType,"Dinosaurs are a diverse group of reptiles[note 1] of the clade Dinosauria. They first appeared during the Triassic period, between 243 and 233.23 million years ago, although the exact origin and timing of the evolution of dinosaurs is the subject of active research. They became the dominant terrestrial vertebrates after the Triassic–Jurassic extinction event 201.3 million years ago; their dominance continued throughout the Jurassic and Cretaceous periods. The fossil record shows that birds are modern feathered dinosaurs, having evolved from earlier theropods during the Late Jurassic epoch, and are the only dinosaur lineage to survive the Cretaceous–Paleogene extinction event approximately 66 million years ago. Dinosaurs can therefore be divided into avian dinosaurs, or birds; and non-avian dinosaurs, which are all dinosaurs other than birds.\n" +
                "\n" +
                "Dinosaurs are a varied group of animals from taxonomic, morphological and ecological standpoints. Using fossil evidence, paleontologists have identified over 900 distinct genera and more than 1,000 different species of non-avian dinosaurs. Dinosaurs are represented on every continent by both extant species (birds) and fossil remains. Through the first half of the 20th century, before birds were recognized to be dinosaurs, most of the scientific community believed dinosaurs to have been sluggish and cold-blooded. Most research conducted since the 1970s, however, has indicated that all dinosaurs were active animals with elevated metabolisms and numerous adaptations for social interaction. Some were herbivorous, others carnivorous. Evidence suggests that all dinosaurs were egg-laying; and that nest-building was a trait shared by many dinosaurs, both avian and non-avian.\n" +
                "\n" +
                "While dinosaurs were ancestrally bipedal, many extinct groups included quadrupedal species, and some were able to shift between these stances. Elaborate display structures such as horns or crests are common to all dinosaur groups, and some extinct groups developed skeletal modifications such as bony armor and spines. While the dinosaurs' modern-day surviving avian lineage (birds) are generally small due to the constraints of flight, many prehistoric dinosaurs (non-avian and avian) were large-bodied—the largest sauropod dinosaurs are estimated to have reached lengths of 39.7 meters (130 feet) and heights of 18 m (59 ft) and were the largest land animals of all time. Still, the idea that non-avian dinosaurs were uniformly gigantic is a misconception based in part on preservation bias, as large, sturdy bones are more likely to last until they are fossilized. Many dinosaurs were quite small, some of them only measured about 50 centimeters (20 inches) long.\n" +
                "\n" +
                "The first dinosaur fossils were recognized in the early 19th century, with the name \"dinosaur\" (meaning \"terrible lizard\") having been coined by Sir Richard Owen in 1841 to refer to these \"great fossil lizards\". Since then, mounted fossil dinosaur skeletons have been major attractions at museums worldwide, and dinosaurs have become an enduring part of popular culture. The large sizes of some dinosaurs, as well as their seemingly monstrous and fantastic nature, have ensured their regular appearance in best-selling books and films, such as Jurassic Park. Persistent public enthusiasm for the animals has resulted in significant funding for dinosaur science, and new discoveries are regularly covered by the media. "));
        booksDatabase.insert(new Books(R.drawable.european_history,"European History"," Adams Smith",5,0,historyType,"Ancient history as a term refers to the aggregate of past events[1] from the beginning of writing and recorded human history and extending as far as post-classical history. The phrase may be used either to refer to the period of time or the academic discipline.\n" +
                "\n" +
                "The span of recorded history is roughly 5,000 years, beginning with the Sumerian cuneiform script, with the oldest coherent texts from about 2600 BC.[2] Ancient history covers all continents inhabited by humans in the period 3000 BC – AD 500.\n" +
                "\n" +
                "The broad term \"ancient history\" is not to be confused with \"classical antiquity\". The term classical antiquity is often used to refer to Western history in the Ancient Mediterranean from the beginning of recorded Greek history in 776 BC (first Olympiad). This roughly coincides with the traditional date of the founding of Rome in 753 BC, the beginning of the history of ancient Rome, and the beginning of the Archaic period in Ancient Greece.\n" +
                "\n" +
                "The academic term \"history\" is not to be confused with colloquial references to times past. History is fundamentally the study of the past, and can be either scientific (archaeology) or humanistic (history through language).\n" +
                "\n" +
                "Although the ending date of ancient history is disputed, some Western scholars use the fall of the Western Roman Empire in 476 AD (the most used),[3][4] the closure of the Platonic Academy in 529 AD,[5] the death of the emperor Justinian I in 565 AD,[6] the coming of Islam,[7] or the rise of Charlemagne[8] as the end of ancient and Classical European history. Outside of Europe the 450–500 time frame for the end of ancient times has had difficulty as a transition date from ancient to post-classical times.\n" +
                "\n" +
                "During the time period of ancient history (starting roughly from 3000 BC), the world population was already exponentially increasing due to the Neolithic Revolution, which was in full progress. According to HYDE estimates from the Netherlands, world population increased exponentially in this period. In 10,000 BC in prehistory, the world population had stood at 2 million, rising to 45 million by 3,000 BC. By the rise of the Iron Age in 1,000 BC, the population had risen to 72 million. By the end of the period in 500 AD, the world population is thought to have stood at 209 million. In 3,500 years, the world population increased by 100 times."));
        booksDatabase.insert(new Books(R.drawable.dinasours,"Dinosaurs","Selena Adams",3,0,kidsType,"Dinosaurs are a diverse group of reptiles[note 1] of the clade Dinosauria. They first appeared during the Triassic period, between 243 and 233.23 million years ago, although the exact origin and timing of the evolution of dinosaurs is the subject of active research. They became the dominant terrestrial vertebrates after the Triassic–Jurassic extinction event 201.3 million years ago; their dominance continued throughout the Jurassic and Cretaceous periods. The fossil record shows that birds are modern feathered dinosaurs, having evolved from earlier theropods during the Late Jurassic epoch, and are the only dinosaur lineage to survive the Cretaceous–Paleogene extinction event approximately 66 million years ago. Dinosaurs can therefore be divided into avian dinosaurs, or birds; and non-avian dinosaurs, which are all dinosaurs other than birds.\n" +
                "\n" +
                "Dinosaurs are a varied group of animals from taxonomic, morphological and ecological standpoints. Using fossil evidence, paleontologists have identified over 900 distinct genera and more than 1,000 different species of non-avian dinosaurs. Dinosaurs are represented on every continent by both extant species (birds) and fossil remains. Through the first half of the 20th century, before birds were recognized to be dinosaurs, most of the scientific community believed dinosaurs to have been sluggish and cold-blooded. Most research conducted since the 1970s, however, has indicated that all dinosaurs were active animals with elevated metabolisms and numerous adaptations for social interaction. Some were herbivorous, others carnivorous. Evidence suggests that all dinosaurs were egg-laying; and that nest-building was a trait shared by many dinosaurs, both avian and non-avian.\n" +
                "\n" +
                "While dinosaurs were ancestrally bipedal, many extinct groups included quadrupedal species, and some were able to shift between these stances. Elaborate display structures such as horns or crests are common to all dinosaur groups, and some extinct groups developed skeletal modifications such as bony armor and spines. While the dinosaurs' modern-day surviving avian lineage (birds) are generally small due to the constraints of flight, many prehistoric dinosaurs (non-avian and avian) were large-bodied—the largest sauropod dinosaurs are estimated to have reached lengths of 39.7 meters (130 feet) and heights of 18 m (59 ft) and were the largest land animals of all time. Still, the idea that non-avian dinosaurs were uniformly gigantic is a misconception based in part on preservation bias, as large, sturdy bones are more likely to last until they are fossilized. Many dinosaurs were quite small, some of them only measured about 50 centimeters (20 inches) long.\n" +
                "\n" +
                "The first dinosaur fossils were recognized in the early 19th century, with the name \"dinosaur\" (meaning \"terrible lizard\") having been coined by Sir Richard Owen in 1841 to refer to these \"great fossil lizards\". Since then, mounted fossil dinosaur skeletons have been major attractions at museums worldwide, and dinosaurs have become an enduring part of popular culture. The large sizes of some dinosaurs, as well as their seemingly monstrous and fantastic nature, have ensured their regular appearance in best-selling books and films, such as Jurassic Park. Persistent public enthusiasm for the animals has resulted in significant funding for dinosaur science, and new discoveries are regularly covered by the media. "));
        booksDatabase.insert(new Books(R.drawable.intro,"Intro To Programing","Michael Owen",3,0,programingType,"After winning a Westinghouse Talent Search scholarship, Knuth enrolled at the Case Institute of Technology (now Case Western Reserve University), where his performance was so outstanding that the faculty voted to award him a master of science upon his completion of the baccalaureate degree. During his summer vacations, Knuth was hired by the Burroughs Corporation to write compilers, earning more in his summer months than full professors did for an entire year.[4] Such exploits made Knuth a topic of discussion among the mathematics department, which included Richard S. Varga.\n" +
                "\n" +
                "In January 1962, when he was a graduate student in the mathematics department at Caltech, Knuth was approached by Addison-Wesley to write a book about compiler design, and he proposed a larger scope. He came up with a list of 12 chapter titles the same day. In the summer of 1962 he worked on a FORTRAN compiler for UNIVAC. During this time, he also came up with a mathematical analysis of linear probing, which convinced him to present the material with a quantitative approach. After receiving his PhD in June 1963, he began working on his manuscript, of which he finished his first draft in June 1965, at 3000 hand-written pages.[5] He had assumed that about five hand-written pages would translate into one printed page, but his publisher said instead that about \u200B1 1⁄2 hand-written pages translated to one printed page. This meant he had approximately 2000 printed pages of material, which closely matches the size of the first three published volumes. The publisher was nervous about accepting such a project from a graduate student. At this point, Knuth received support from Richard S. Varga, who was the scientific adviser to the publisher. Varga was visiting Olga Taussky-Todd and John Todd at Caltech. With Varga's enthusiastic endorsement, the publisher accepted Knuth's expanded plans. In its expanded version, the book would be published in seven volumes, each with just one or two chapters.[6] Due to the growth in the material, the plan for Volume 4 has since expanded to include Volumes 4A, 4B, 4C, 4D, and possibly more.\n" +
                "\n" +
                "In 1976, Knuth prepared a second edition of Volume 2, requiring it to be typeset again, but the style of type used in the first edition (called hot type) was no longer available. In 1977, he decided to spend some time creating something more suitable. Eight years later, he returned with TEX, which is currently used for all volumes.\n" +
                "\n" +
                "The offer of a so-called Knuth reward check worth \"one hexadecimal dollar\" (100HEX base 16 cents, in decimal, is $2.56) for any errors found, and the correction of these errors in subsequent printings, has contributed to the highly polished and still-authoritative nature of the work, long after its first publication. Another characteristic of the volumes is the variation in the difficulty of the exercises. Knuth even has a numerical difficulty scale for rating those exercises, varying from 0 to 50, where 0 is trivial, and 50 is an open question in contemporary research. [7]\n" +
                "\n" +
                "Knuth's dedication reads: "));
        booksDatabase.insert(new Books(R.drawable.islam,"The History Of Islam","Ahmed Maged",5,0,historyType,"The history of Islam concerns the political, social, economic and cultural developments of Islamic civilization. Most historians[1] accept that Islam originated in Mecca and Medina at the start of the 7th century CE. Muslims regard Islam as a return to the original faith of the prophets, such as Jesus, Solomon, David, Moses, Abraham, Noah and Adam, with the submission (islam) to the will of God.[2][3][4]\n" +
                "\n" +
                "According to tradition, in 610 CE, the Islamic Prophet Muhammad began receiving what Muslims consider to be divine revelations, calling for submission to the one God, the expectation of the imminent Last Judgement, and caring for the poor and needy.[5] Muhammad's message won over a handful of followers and was met with increasing opposition from Meccan notables.[6] In 622, a few years after losing protection with the death of his influential uncle Abu Talib, Muhammad migrated to the city of Yathrib (now known as Medina). With Muhammad's death in 632, disagreement broke out over who would succeed him as leader of the Muslim community during the Rashidun Caliphate.\n" +
                "\n" +
                "By the 8th century, the Umayyad Caliphate extended from Iberia in the west to the Indus River in the east. Polities such as those ruled by the Umayyads and Abbasid Caliphate (in the Middle East and later in Spain and Southern Italy), Fatimids, Seljuks, Ayyubids and Mamluks were among the most influential powers in the world. Highly persianized empires built by the Samanids, Ghaznavids, Ghurids made significant developments. The Islamic Golden Age gave rise to many centers of culture and science and produced notable polymaths, astronomers, mathematicians, physicians and philosophers during the Middle Ages.\n" +
                "\n" +
                "By the early 13th century, the Delhi Sultanate conquered the northern Indian subcontinent, while Turkic dynasties like the Sultanate of Rum and Artuqids conquered much of Anatolia from the Byzantine Empire throughout the 11th and 12th centuries. In the 13th and 14th centuries, destructive Mongol invasions and those of Tamerlane (Timur) from the East, along with the loss of population in the Black Death, greatly weakened the traditional centers of the Muslim world, stretching from Persia to Egypt, but saw the emergence of the Timurid Renaissance and major global economic powers such as West Africa's Mali Empire and South Asia's Bengal Sultanate.[7][8][9] Following the deportation and enslavement of the Muslim Moors from the Emirate of Sicily and other Italian territories,[10] the Islamic Spain was gradually conquered by Christian forces during the Reconquista. Nonetheless, in the Early Modern period, the states of the Age of the Islamic Gunpowders—the Ottoman Turkey, Safavid Iran and Mughal India—emerged as great world powers.\n" +
                "\n" +
                "During the 19th and early 20th centuries, most of the Islamic world fell under the influence or direct control of European \"Great Powers.\" Their efforts to win independence and build modern nation-states over the course of the last two centuries continue to reverberate to the present day, as well as fuel conflict-zones in regions such as Palestine, Kashmir, Xinjiang, Chechnya, Central Africa, Bosnia and Myanmar. The Oil boom stabilized the Arab states of the Persian Gulf, making them the world's largest oil producers and exporters, which focus on free trade and tourism.[11][12] "));
        booksDatabase.insert(new Books(R.drawable.java,"Java Programing","Adams Costa",4,0,programingType,"This book is an introduction to programming in Oracle’s Java™ programming language, a widely used programming language and software platform. This book serves as a comprehensive guide, complete with a series of tutorials to help users better understand the many ways one can program in Java. In its entirety, this book is meant to be both an introductory guide and a useful reference on Java and related technologies. As is the nature of this book, the content within the book is continuously being updated and revised. With every chapter within this book, the complexity of the context increases, building up on lessons learnt in the previous chapters. Beginners should therefore start from the beginning and proceed in a sequence throughout the material of the book.\n" +
                "\n" +
                "If you are not familiar with object-oriented programming, you should first read the book Object Oriented Programming. Other special purpose books on Java, such as Jakarta EE enterprise programming, Java Persistence, or Java Swing programming, with more details, would complement this book nicely. "));
        booksDatabase.insert(new Books(R.drawable.life_mars,"Life On Mars","Selena Adams",1,0,kidsType,"The possibility of life on Mars is a subject of huge interest in astrobiology due to its proximity and similarities to Earth. To date, no proof has been found of past or present life on Mars. Cumulative evidence shows that during the ancient Noachian time period, the surface environment of Mars had liquid water and may have been habitable for microorganisms. The existence of habitable conditions does not necessarily indicate the presence of life.[1][2]\n" +
                "\n" +
                "Scientific searches for evidence of life began in the 19th century and continue today via telescopic investigations and deployed probes. While early work focused on phenomenology and bordered on fantasy, the modern scientific inquiry has emphasized the search for water, chemical biosignatures in the soil and rocks at the planet's surface, and biomarker gases in the atmosphere.[3]\n" +
                "\n" +
                "Mars is of particular interest for the study of the origins of life because of its similarity to the early Earth. This is especially so since Mars has a cold climate and lacks plate tectonics or continental drift, so has remained almost unchanged since the end of the Hesperian period. At least two thirds of Mars' surface is more than 3.5 billion years old, and Mars may thus hold the best record of the prebiotic conditions leading to life, even if life does not or has never existed there,[4][5] which might have started developing as early as 4.48 billion years ago.[6]\n" +
                "\n" +
                "Following the confirmation of the past existence of surface liquid water, the Curiosity and Opportunity rovers started searching for evidence of past life, including a past biosphere based on autotrophic, chemotrophic, or chemolithoautotrophic microorganisms, as well as ancient water, including fluvio-lacustrine environments (plains related to ancient rivers or lakes) that may have been habitable.[7][8][9][10] The search for evidence of habitability, taphonomy (related to fossils), and organic compounds on Mars is now a primary NASA and ESA objective.\n" +
                "\n" +
                "The findings of organic compounds inside sedimentary rocks and of boron on Mars are of interest as they are precursors for prebiotic chemistry. Such findings, along with previous discoveries that liquid water was clearly present on ancient Mars, further supports the possible early habitability of Gale Crater on Mars.[11][12] Currently, the surface of Mars is bathed with ionizing radiation, and Martian soil is rich in perchlorates toxic to microorganisms.[13][14] Therefore, the consensus is that if life exists—or existed—on Mars, it could be found or is best preserved in the subsurface, away from present-day harsh surface processes.\n" +
                "\n" +
                "In June 2018, NASA announced the detection of seasonal variation of methane levels on Mars. Methane could be produced by microorganisms or by geological means.[15] The European ExoMars Trace Gas Orbiter started mapping the atmospheric methane in April 2018, and the 2022 ExoMars rover Rosalind Franklin will drill and analyze subsurface samples, while the NASA Mars 2020 rover Perseverance will cache dozens of drill samples for their potential transport to Earth laboratories in the late 2020s or 2050s. "));
        booksDatabase.insert(new Books(R.drawable.php,"PHP Guide","Lena Walker",1,0,programingType,"PHP is a general-purpose scripting language especially suited to web development.[5] It was originally created by Danish-Canadian programmer Rasmus Lerdorf in 1994.[6] The PHP reference implementation is now produced by The PHP Group.[7] PHP originally stood for Personal Home Page,[6] but it now stands for the recursive initialism PHP: Hypertext Preprocessor.[8]\n" +
                "\n" +
                "PHP code is usually processed on a web server by a PHP interpreter implemented as a module, a daemon or as a Common Gateway Interface (CGI) executable. On a web server, the result of the interpreted and executed PHP code – which may be any type of data, such as generated HTML or binary image data – would form the whole or part of an HTTP response. Various web template systems, web content management systems, and web frameworks exist which can be employed to orchestrate or facilitate the generation of that response. Additionally, PHP can be used for many programming tasks outside of the web context, such as standalone graphical applications[9] and robotic drone control.[10] Arbitrary PHP code can also be interpreted and executed via command-line interface (CLI).\n" +
                "\n" +
                "The standard PHP interpreter, powered by the Zend Engine, is free software released under the PHP License. PHP has been widely ported and can be deployed on most web servers on almost every operating system and platform, free of charge.[11]\n" +
                "\n" +
                "The PHP language evolved without a written formal specification or standard until 2014, with the original implementation acting as the de facto standard which other implementations aimed to follow. Since 2014, work has gone on to create a formal PHP specification.[12]\n" +
                "\n" +
                "As of January 2021, 72% of PHP websites use discontinued versions of PHP, i.e. PHP 7.2 or lower, which are no longer supported by The PHP Development Team. A large additional fraction uses PHP 7.3, which is only (up to December 6, 2021) \"supported for critical security issues only.\"[13] Over 40% of all PHP websites use version 5.6 or older,[14] that not even Debian supports (Debian 9 supported version 7.0 and 7.1).[15] "));
        booksDatabase.insert(new Books(R.drawable.planets,"Planets","Selena Adams",3,0,kidsType,"The possibility of life on Other Planets is a subject of huge interest in astrobiology due to its proximity and similarities to Earth. To date, no proof has been found of past or present life on Mars. Cumulative evidence shows that during the ancient Noachian time period, the surface environment of Mars had liquid water and may have been habitable for microorganisms. The existence of habitable conditions does not necessarily indicate the presence of life.[1][2]\n" +
                "\n" +
                "Scientific searches for evidence of life began in the 19th century and continue today via telescopic investigations and deployed probes. While early work focused on phenomenology and bordered on fantasy, the modern scientific inquiry has emphasized the search for water, chemical biosignatures in the soil and rocks at the planet's surface, and biomarker gases in the atmosphere.[3]\n" +
                "\n" +
                "Mars is of particular interest for the study of the origins of life because of its similarity to the early Earth. This is especially so since Mars has a cold climate and lacks plate tectonics or continental drift, so has remained almost unchanged since the end of the Hesperian period. At least two thirds of Mars' surface is more than 3.5 billion years old, and Mars may thus hold the best record of the prebiotic conditions leading to life, even if life does not or has never existed there,[4][5] which might have started developing as early as 4.48 billion years ago.[6]\n" +
                "\n" +
                "Following the confirmation of the past existence of surface liquid water, the Curiosity and Opportunity rovers started searching for evidence of past life, including a past biosphere based on autotrophic, chemotrophic, or chemolithoautotrophic microorganisms, as well as ancient water, including fluvio-lacustrine environments (plains related to ancient rivers or lakes) that may have been habitable.[7][8][9][10] The search for evidence of habitability, taphonomy (related to fossils), and organic compounds on Mars is now a primary NASA and ESA objective.\n" +
                "\n" +
                "The findings of organic compounds inside sedimentary rocks and of boron on Mars are of interest as they are precursors for prebiotic chemistry. Such findings, along with previous discoveries that liquid water was clearly present on ancient Mars, further supports the possible early habitability of Gale Crater on Mars.[11][12] Currently, the surface of Mars is bathed with ionizing radiation, and Martian soil is rich in perchlorates toxic to microorganisms.[13][14] Therefore, the consensus is that if life exists—or existed—on Mars, it could be found or is best preserved in the subsurface, away from present-day harsh surface processes.\n" +
                "\n" +
                "In June 2018, NASA announced the detection of seasonal variation of methane levels on Mars. Methane could be produced by microorganisms or by geological means.[15] The European ExoMars Trace Gas Orbiter started mapping the atmospheric methane in April 2018, and the 2022 ExoMars rover Rosalind Franklin will drill and analyze subsurface samples, while the NASA Mars 2020 rover Perseverance will cache dozens of drill samples for their potential transport to Earth laboratories in the late 2020s or 2050s. "));
        booksDatabase.insert(new Books(R.drawable.programing_crystal,"Programing Crystal","Oliver Mega",3,0,programingType," Programming design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.[27]\n" +
                "\n" +
                "Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly, procedural), object-oriented and functional programming. Python is often described as a \"batteries included\" language due to its comprehensive standard library.[28]\n" +
                "\n" +
                "Python was created in the late 1980s, and first released in 1991, by Guido van Rossum as a successor to the ABC programming language. Python 2.0, released in 2000, introduced new features, such as list comprehensions, and a garbage collection system with reference counting, and was discontinued with version 2.7 in 2020.[29] Python 3.0, released in 2008, was a major revision of the language that is not completely backward-compatible and much Python 2 code does not run unmodified on Python 3. With Python 2's end-of-life, only Python 3.6.x[30] and later are supported, with older versions still supporting e.g. Windows 7 (and old installers not restricted to 64-bit Windows).\n" +
                "\n" +
                "Python interpreters are supported for mainstream operating systems and available for a few more (and in the past supported many more). A global community of programmers develops and maintains CPython, a free and open-source[31] reference implementation. A non-profit organization, the Python Software Foundation, manages and directs resources for Python and CPython development.\n" +
                "\n" +
                "As of December 2020 Python ranked third in TIOBE’s index of most popular programming languages, behind C and Java.[32] "));
        booksDatabase.insert(new Books(R.drawable.python,"Python","Aron Ramsey",5,0,programingType,"Python is an interpreted, high-level and general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.[27]\n" +
                "\n" +
                "Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly, procedural), object-oriented and functional programming. Python is often described as a \"batteries included\" language due to its comprehensive standard library.[28]\n" +
                "\n" +
                "Python was created in the late 1980s, and first released in 1991, by Guido van Rossum as a successor to the ABC programming language. Python 2.0, released in 2000, introduced new features, such as list comprehensions, and a garbage collection system with reference counting, and was discontinued with version 2.7 in 2020.[29] Python 3.0, released in 2008, was a major revision of the language that is not completely backward-compatible and much Python 2 code does not run unmodified on Python 3. With Python 2's end-of-life, only Python 3.6.x[30] and later are supported, with older versions still supporting e.g. Windows 7 (and old installers not restricted to 64-bit Windows).\n" +
                "\n" +
                "Python interpreters are supported for mainstream operating systems and available for a few more (and in the past supported many more). A global community of programmers develops and maintains CPython, a free and open-source[31] reference implementation. A non-profit organization, the Python Software Foundation, manages and directs resources for Python and CPython development.\n" +
                "\n" +
                "As of December 2020 Python ranked third in TIOBE’s index of most popular programming languages, behind C and Java.[32] "));
        booksDatabase.insert(new Books(R.drawable.rockets,"Rockets","Amr Ehab",2,0,kidsType,"The ROCKETS is a subject of huge interest in astrobiology due to its proximity and similarities to Earth. To date, no proof has been found of past or present life on Mars. Cumulative evidence shows that during the ancient Noachian time period, the surface environment of Mars had liquid water and may have been habitable for microorganisms. The existence of habitable conditions does not necessarily indicate the presence of life.[1][2]\n" +
                "\n" +
                "Scientific searches for evidence of life began in the 19th century and continue today via telescopic investigations and deployed probes. While early work focused on phenomenology and bordered on fantasy, the modern scientific inquiry has emphasized the search for water, chemical biosignatures in the soil and rocks at the planet's surface, and biomarker gases in the atmosphere.[3]\n" +
                "\n" +
                "Mars is of particular interest for the study of the origins of life because of its similarity to the early Earth. This is especially so since Mars has a cold climate and lacks plate tectonics or continental drift, so has remained almost unchanged since the end of the Hesperian period. At least two thirds of Mars' surface is more than 3.5 billion years old, and Mars may thus hold the best record of the prebiotic conditions leading to life, even if life does not or has never existed there,[4][5] which might have started developing as early as 4.48 billion years ago.[6]\n" +
                "\n" +
                "Following the confirmation of the past existence of surface liquid water, the Curiosity and Opportunity rovers started searching for evidence of past life, including a past biosphere based on autotrophic, chemotrophic, or chemolithoautotrophic microorganisms, as well as ancient water, including fluvio-lacustrine environments (plains related to ancient rivers or lakes) that may have been habitable.[7][8][9][10] The search for evidence of habitability, taphonomy (related to fossils), and organic compounds on Mars is now a primary NASA and ESA objective.\n" +
                "\n" +
                "The findings of organic compounds inside sedimentary rocks and of boron on Mars are of interest as they are precursors for prebiotic chemistry. Such findings, along with previous discoveries that liquid water was clearly present on ancient Mars, further supports the possible early habitability of Gale Crater on Mars.[11][12] Currently, the surface of Mars is bathed with ionizing radiation, and Martian soil is rich in perchlorates toxic to microorganisms.[13][14] Therefore, the consensus is that if life exists—or existed—on Mars, it could be found or is best preserved in the subsurface, away from present-day harsh surface processes.\n" +
                "\n" +
                "In June 2018, NASA announced the detection of seasonal variation of methane levels on Mars. Methane could be produced by microorganisms or by geological means.[15] The European ExoMars Trace Gas Orbiter started mapping the atmospheric methane in April 2018, and the 2022 ExoMars rover Rosalind Franklin will drill and analyze subsurface samples, while the NASA Mars 2020 rover Perseverance will cache dozens of drill samples for their potential transport to Earth laboratories in the late 2020s or 2050s. "));
        booksDatabase.insert(new Books(R.drawable.space,"Space","Sam Mohsen",1,0,kidsType,"The ROCKETS is a subject of huge interest in astrobiology due to its proximity and similarities to Earth. To date, no proof has been found of past or present life on Mars. Cumulative evidence shows that during the ancient Noachian time period, the surface environment of Mars had liquid water and may have been habitable for microorganisms. The existence of habitable conditions does not necessarily indicate the presence of life.[1][2]\n" +
                "\n" +
                "Scientific searches for evidence of life began in the 19th century and continue today via telescopic investigations and deployed probes. While early work focused on phenomenology and bordered on fantasy, the modern scientific inquiry has emphasized the search for water, chemical biosignatures in the soil and rocks at the planet's surface, and biomarker gases in the atmosphere.[3]\n" +
                "\n" +
                "Mars is of particular interest for the study of the origins of life because of its similarity to the early Earth. This is especially so since Mars has a cold climate and lacks plate tectonics or continental drift, so has remained almost unchanged since the end of the Hesperian period. At least two thirds of Mars' surface is more than 3.5 billion years old, and Mars may thus hold the best record of the prebiotic conditions leading to life, even if life does not or has never existed there,[4][5] which might have started developing as early as 4.48 billion years ago.[6]\n" +
                "\n" +
                "Following the confirmation of the past existence of surface liquid water, the Curiosity and Opportunity rovers started searching for evidence of past life, including a past biosphere based on autotrophic, chemotrophic, or chemolithoautotrophic microorganisms, as well as ancient water, including fluvio-lacustrine environments (plains related to ancient rivers or lakes) that may have been habitable.[7][8][9][10] The search for evidence of habitability, taphonomy (related to fossils), and organic compounds on Mars is now a primary NASA and ESA objective.\n" +
                "\n" +
                "The findings of organic compounds inside sedimentary rocks and of boron on Mars are of interest as they are precursors for prebiotic chemistry. Such findings"));
        booksDatabase.insert(new Books(R.drawable.weather,"Weather","Maguire David",3,0,kidsType,"Weather is a 2020 novel by American writer Jenny Offill. The novel is narrated by a college librarian, Lizzie. The book takes place before and after Donald Trump becomes president of the United States and depicts Lizzie's family life and her concerns about climate change. The novel received mostly positive reviews, with favorable comparisons to Offill's previous novel, Dept. of Speculation and praise for its structure. "));
        booksDatabase.insert(new Books(R.drawable.world_history,"World History","Amr Ehab",4,0,historyType,"Ancient history as a term refers to the aggregate of past events[1] from the beginning of writing and recorded human history and extending as far as post-classical history. The phrase may be used either to refer to the period of time or the academic discipline.\n" +
                "\n" +
                "The span of recorded history is roughly 5,000 years, beginning with the Sumerian cuneiform script, with the oldest coherent texts from about 2600 BC.[2] Ancient history covers all continents inhabited by humans in the period 3000 BC – AD 500.\n" +
                "\n" +
                "The broad term \"ancient history\" is not to be confused with \"classical antiquity\". The term classical antiquity is often used to refer to Western history in the Ancient Mediterranean from the beginning of recorded Greek history in 776 BC (first Olympiad). This roughly coincides with the traditional date of the founding of Rome in 753 BC, the beginning of the history of ancient Rome, and the beginning of the Archaic period in Ancient Greece.\n" +
                "\n" +
                "The academic term \"history\" is not to be confused with colloquial references to times past. History is fundamentally the study of the past, and can be either scientific (archaeology) or humanistic (history through language).\n" +
                "\n" +
                "Although the ending date of ancient history is disputed, some Western scholars use the fall of the Western Roman Empire in 476 AD "));







    }
  /* public boolean insertBooksIntoDatabase(){
        booksDatabase.insert(new Books())
    }*/


}
